name: Deploy
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "console\\.log\\(([^)]+)\\)"
          replace: ""
          regex: "true"

      # Add your deployment steps here
